
import { Course } from './course';
export const COURSES:Course []=[
    {   id:1 ,
        name:"angular",
        ranking:4,
        level:"beginner",
        language:"english",
        teacherId:1,
        detailId:1,
        price:60,
        title:"Angular-The Complete Guide (2021 Edition)"
     },
     {   id:2 ,
        name:"angular" ,
        ranking:4,
        level:"intermediate",
        language:"urdu",
        teacherId:1,
        detailId:1,
        price:70,
        title:"The Complete Angular Course: Beginner to Advanced"
     },
     {   id:3 ,
        name:"angular" ,
        ranking:3,
        level:"expert",
        language:"french",
        teacherId:1,
        detailId:1,
        price:80,
        title:"Angular Crash Course for Busy Developers"
     },


     {   id:4 ,
        name:"reactjs" ,
        ranking:4,
        level:"beginner",
        language:"english",
        teacherId:2,
        detailId:2,
        price:60,
        title:"React-The Complete Guide(incl Hooks,React Router,Redux)"
     },
     {   id:5 ,
        name:"reactjs" ,
        ranking:4,
        level:"intermediate",
        language:"urdu",
        teacherId:2,
        detailId:2,
        price:70,
        title:"Next.js & React -The Complete Guide(incl.Two Paths!)"
     },
     {  id:6,
        name:"reactjs",
        ranking:3,
        level:"expert",
        language:"french",
        teacherId:2,
        detailId:2,
        price:80,
        title:"React JS,Angular & Vue JS -Quickstart & Comparison"
     },


     {  id:7 ,
        name:"net" ,
        ranking:4,
        level:"beginner",
        language:"english",
        teacherId:3,
        detailId:3,
        price:60,
        title:"Build an app with ASPNET Core and Angular from scratch"
     },
     {  id:8 ,
        name:"net" ,
        ranking:4,
        level:"intermediate",
        language:"urdu",
        teacherId:3,
        detailId:3,
        price:70,
        title:"The Complete ASP.NET MVC 5 Course"
     },
     {  id:9,
        name:"net",
        ranking:3,
        level:"expert",
        language:"french",
        teacherId:3,
        detailId:3,
        price:80,
        title:"Microservices Observability,Resilience, Monitoring on .Net"
     },


     {  id:10 ,
        name:"sql" ,
        ranking:4,
        level:"beginner",
        language:"english",
        teacherId:4,
        detailId:4,
        price:60,
        title:"The Complete SQL Bootcamp 2021:Go from Zero to Hero"
     },
     {  id:11 ,
        name:"sql" ,
        ranking:4,
        level:"intermediate",
        language:"urdu",
        teacherId:4,
        detailId:4,
        price:70,
        title:"SQL-MySQL for Data Analytics and Business Intelligence"
     },
     {  id:12,
        name:"sql",
        ranking:3,
        level:"expert",
        language:"french",
        teacherId:4,
        detailId:4,
        price:80,
        title:"SQL for Beginners: Learn SQL using MySQL"
     },


     {  id:13 ,
        name:"express" ,
        ranking:4,
        level:"beginner",
        language:"english",
        teacherId:5,
        detailId:5,
        price:60,
        title:"Full Stack React Js with Redux, Node.Js, Express.Js"
     },
     {  id:14 ,
        name:"express" ,
        ranking:4,
        level:"intermediate",
        language:"urdu",
        teacherId:5,
        detailId:5,
        price:70,
        title:"Complete LMS Admin Panel in Node & Express Js"
     },
     {  id:15,
        name:"express",
        ranking:3,
        level:"expert",
        language:"french",
        teacherId:5,
        detailId:5,
        price:80,
        title:" Node.js :/Node.js/Express.js/MongoDB/API"
     },



     
     {  id:16 ,
        name:"node" ,
        ranking:4,
        level:"beginner",
        language:"english",
        teacherId:6,
        detailId:6,
        price:60,
        title:"The Node.js Developer Course (3rd Edition)"
     },
     {  id:17 ,
        name:"node" ,
        ranking:4,
        level:"intermediate",
        language:"urdu",
        teacherId:6,
        detailId:6,
        price:70,
        title:"NodeJS-(MVC,REST APIs,GraphQL,Deno)"
     },
     {  id:18,
        name:"node",
        ranking:3,
        level:"expert",
        language:"french",
        teacherId:6,
        detailId:6,
        price:80,
        title:"Learn and Understand NodeJS"
     },


     {  id:19 ,
        name:"mean stack" ,
        ranking:4,
        level:"beginner",
        language:"english",
        teacherId:7,
        detailId:7,
        price:60,
        title:"Angular & NodeJS-The MEAN Stack[2021 Edition]"
     },
     {  id:20 ,
        name:"mean stack" ,
        ranking:4,
        level:"intermediate",
        language:"urdu",
        teacherId:7,
        detailId:7,
        price:70,
        title:"MEAN Stack E-Commerce App PrimeNg [2021]"
     },
     {  id:21,
        name:"mean stack",
        ranking:3,
        level:"expert",
        language:"french",
        teacherId:7,
        detailId:7,
        price:80,
        title:"Become a MEAN Stack Developer"
     }
]

