import { Detail } from './detail';
export const DETAIL:Detail[]=[
    {   id:1,
        name:"Angular",
        img:"assets/courses/angular.jpg",
        totalHours:55,
        totalQuizzes:12,
        totalAssignments:7,
        topics:[
            "One-way Dataflow and Immutability",
           "Attribute and Structural Directives",
            "Component Life Cycle Hooks",
            "Http and Observable Services",
            "Smart/Dumb Component Architecture",
            "Application Structure and Best Practices",
            "Template Binding Syntax",
            "Feature Modules and Routing",
            "Forms and Validation (Reactive Forms and Validators)",
            "Content Projection",
            "onPush Change Detection",
            "Route Guards, Pre-loads, Lazy-loading",
             "Custom Pipes",
            "@viewChild and @ContentChild Decorators",
            "Dynamic Components and ng-template",
            "Dependency Injection and Zones"],
        intro:"AngularJS is a JavaScript-based open-source front-end web framework mainly maintained by Google and by a community of individuals and corporations to address many of the challenges encountered in developing single-page applications.It aims to simplify both the development and the testing of such applications by providing a framework for client-side model–view–controller (MVC) and model–view–viewmodel (MVVM) architectures, along with components commonly used in web applications and progressive web applications.AngularJS is used as the frontend of the MEAN stack, consisting of MongoDB database,Express.js web application server framework, AngularJS itself (or Angular), and Node.js server runtime environment.",
        prerequisites:"NULL",
        studentsEnrolled:8092,
        DateAdded:"01/01/2021",
        discount:"30%"},


    {   id:2,
        name:"React",
        img:"assets/courses/react.png",
        totalHours:64,
        totalQuizzes:15,
        totalAssignments:8,
        topics:[
            "Introduction to ReactJS",
           "React Components",
            "React internals",
            "Component inter communication",
            "Component styling",
            "Unit testing components",
            "Performance optimizations"],
        intro:"React (also known as React.js or ReactJS) is an open-source front-end JavaScript library  for building user interfaces or UI components.It is maintained by Facebook and a community of individual developers and companies. React can be used as a base in the development of single-page or mobile applications. However, React is only concerned with state management and rendering that state to the DOM, so creating React applications usually requires the use of additional libraries for routing, as well as certain client-side functionality.",
        prerequisites:"NULL",
        studentsEnrolled:16041,
        DateAdded:"20/09/2020",
        discount:"15%"},
    {   id:4,
        name:"SQL",
        img:"assets/courses/sql.png",
        totalHours:39,
        totalQuizzes:10,
        totalAssignments:10,
        topics:[ "Key elements of a database.",
        "Relational Keys.",
        "Joins.",
        "Data Modelling.",
        " Fact and Dimension Table Types.",
        " Pass Value from View to Controller",
        "Star Schema.",
        "Snow Flake Schema.",
        " Dropdown list binding using ajax",
        "Form based authentication",
        "Allow anonymous filter"],
        intro:"Structured Query Language is a domain-specific language used in programming and designed for managing data held in a relational database management system (RDBMS), or for stream processing in a relational data stream management system (RDSMS).t is particularly useful in handling structured data, i.e. data incorporating relations among entities and variables.",
        prerequisites:"NULL",
        studentsEnrolled:20455,
        DateAdded:"30/04/2020",
        discount:"10%"},

        {   id:3,
            name:"MVC.Net",
            img:"assets/courses/net.png",
            totalHours:55,
            totalQuizzes:12,
            totalAssignments:7,
            topics:[
                "Mvc Controller",
                "Mvc View",
                " MVC get and post",
                "Action in form tag",
                " Routing in mvc",
                " Pass Value from View to Controller",
                "MVC form collection",
                "Dropdown in mvc",
                "Strongly view in mvc",
                " Data passing using model",
                "Scaffolding create using linq",
                " Scaffolding edit using linq",
                 "Mvc string length",
                " Dropdown list binding using ajax",
                "Form based authentication",
                "Allow anonymous filter"],
            intro:"ASP.NET MVC is a web application framework developed by Microsoft that implements the model–view–controller (MVC) pattern.It is no longer in active development. It is open-source software, apart from the ASP.NET Web Forms component, which is proprietary.ASP.NET Core has since been released, which unified ASP.NET, ASP.NET MVC, ASP.NET Web API, and ASP.NET Web Pages (a platform using only Razor pages).MVC 6 was abandoned due to Core and is not expected to be released. Core is currentlyplanned to merge into .NET 5.",
            prerequisites:"NULL",
            studentsEnrolled:8092,
            DateAdded:"01/01/2021",
            discount:"60%"},
    
    
        {   id:5,
            name:"express",
            img:"assets/courses/express.png",
            totalHours:64,
            totalQuizzes:15,
            totalAssignments:8,
            topics:[
                "Key elements of a database.",
                "Relational Keys.",
                "Joins.",
                "Data Modelling.",
                " Fact and Dimension Table Types.",
                " Pass Value from View to Controller",
                "Star Schema.",
                "Snow Flake Schema.",
                " Dropdown list binding using ajax",
                "Form based authentication",
                "Allow anonymous filter"],
                intro:"Express.js, or simply Express, is a back end web application framework for Node.js, released as free and open-source software under the MIT License.It is designed for building web applications and APIs. It has been called the de facto standard server framework for Node.js.",
            prerequisites:"NULL",
            studentsEnrolled:16041,
            DateAdded:"20/09/2020",
            discount:"50%"},
        
    
        {   id:6,
            name:"Node",
            img:"assets/courses/node.png",
            totalHours:39,
            totalQuizzes:10,
            totalAssignments:10,
            topics:[
                "Routing and HTTP Methods",
                "Middleware",
                "Cookies",
                "REST API",
                "Scaffolding",
                "Database Connectivity",
                "Templating",
                "Snow Flake Schema",
                "Error Handling",
                "Form based authentication",
                "Allow anonymous filter"],
            intro:"Node.js is an open-source, cross-platform, back-end JavaScript runtime environment that runs on the V8 engine and executes JavaScript code outside a web browser.",
            prerequisites:"NULL",
            studentsEnrolled:20455,
            DateAdded:"21/07/2020",
            discount:"20%"},

       {   id:7,
        name:"mean stack",
        img:"assets/courses/mean.png",
            totalHours:39,
            totalQuizzes:10,
            totalAssignments:10,
            topics:[
                "Introduction to Angular",
                "Components in Angular",
                "Data and Event Binding",
                "Attribute Directives and Property Bindings",
                "Pipes and Data Formatting",
                "Performance Tuning and best practices",
                "Express JS with Middleware",
                "Events and Streams",
                "Introduction to NOSQL DB",
                "Introduction to MongoDB",
                "Static and Dynamic Schemas",
                "Create document",
                "Introduction to JSON",
                "JSON Datatype",
                "Introduction to REST API",
                "Introduction Node.js",
                "Asynchronous events vs. threads"],
            intro:"MEAN (MongoDB, Express.js, AngularJS (or Angular), and Node.js) is a free and open-source JavaScript software stack for building dynamic web sites and web applications.Because all components of the MEAN stack support programs that are written in JavaScript,MEAN applications can be written in one language for both server-side and client-side execution environments.",
            prerequisites:"NULL",
            studentsEnrolled:20455,
            DateAdded:"20/09/2020",
            discount:"33%"}
]